### ISSUE TITLE
Media Control: Bluetooth

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#38]
**Unit test result**

Test Name: Media Control: Bluetooth

Test Procedure:
 1. Media Control > Bluetooth 차단 정책
 2. 정책 수신
 3. Bluetooth 활성화
 4. 차단 확인

Test Environment
 - OS version: Gooroom OS 2.1
 - Kernel version: 4.19.0.9-amd64
 - Agent version: beta 2

Founded bug: 알림창 미발생

**Comment by SomansaOpenSource** [comment]
Cleared issue
