### ISSUE TITLE
Media Control: Removable Device

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#39]
**Unit test result**

Test Name:

Test Procedure:
1. Media Control > Removable Device 차단 정책
2. 정책 수신
3. USB 삽입
4. 차단 확인

Test Environment
- OS version: Gooroom OS 2.1
- Kernel version: 4.19.0.9-amd64
- Agent version: beta 2

Test Result: 성공
Founded bug:

**Comment by SomansaOpenSource** [comment]
check done
