### ISSUE TITLE
Media Control: 무선랜

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#42]
*Unit test result*

Test Name: Media Control: 무선랜

Test Procedure:
1. Media Control > 무선랜 차단 정책
2. 정책 수신
3. 무선랜 활성화 시도
4. 차단 확인

Test Environment

- OS version: Gooroom OS 2.1
- Kernel version: 4.19.0.9-amd64
- Agent version: beta 2

Test Result: 성공
Founded bug:

**Comment by SomansaOpenSource** [comment]
done
