### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#43]
**Unit test result**

Test Name: Discover 

Test Procedure:
1. 속성 설정: /home/discover 
2. 패턴 설정: 주민등록번호 탐지 
3. 정책 수신
4. 해당 경로에 파일 저장
5. 기본검사 수행
6. 검출 결과 확인

Test Environment
- OS version: Gooroom OS 2.1
- Kernel version: 4.19.0.9-amd64
- Agent version: beta 2

Test Result: 성공
Founded bug:

**Comment by SomansaOpenSource** [comment]
done
