### ISSUE TITLE
Copy Prevent: Removable Device

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#44]
**Unit test result**

Test Name: Copy Prevent: Removable Device

Test Procedure:
1. 탐지규칙 생성
2. Copy Prevent 정책 설정(데이터 검사)
3. USB 연결
4. 개인정보 포함된 파일 USB로 복사
5. 차단 확인

Test Environment
- OS version: Gooroom OS 2.1
- Kernel version: 4.19.0.9-amd64
- Agent version: beta 2

Test Result: 성공
Founded bug:

**Comment by SomansaOpenSource** [comment]
done
