### ISSUE TITLE
Test Program: 파일 정보 및 소요시간 로깅

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#45]
관련 모듈: 테스트 프로그램
요청 기능: 성능 측정을 위한 파일 정보 및 소요시간 로깅
기능 상세
 - 파일 이름, 경로, 크기
 - 검사 작업 시작 시각, 종료 시각, 소요 시간
 - 파일당 검사 시작 시각, 종료 시각, 소요 시간
 - 검사 수행한 파일 전체 크기

**Comment by SomansaOpenSource** [comment]
in progress
