### ISSUE TITLE
CONTRIBUTOR LICENSE AGREEMENT 프로세스 부재

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#49]
**Document request**

Document type/name: CONTRIBUTOR_LICENSE_AGREEMENT.MD

Line number(optional)

Contents:
컨트리뷰터 라이선스 동의서는 있으나 명시적 동의 및 제출 프로세스가 없습니다.
동의 및 컨트리뷰터 인적사항을 제출할 수 있는 양식과 프로세스가 필요합니다.

PR #50 참고

**Comment by SomansaOpenSource** [comment]
in progress
