### ISSUE TITLE
File format test(discover): html, xps, odt

### ISSUE THREAD

**Issue by sim1st** [SomansaOpenSource/endpointdlp#54]
**Unit test result**

Test Name:
File format test(discover): html, xps, odt

Test Procedure:
1. Discover 정책 구성시 다음의 포맷 탐지 설정: html, xps, odt
2. 위의 3개 포맷에 해당하는 파일 검사 대상 경로로 이동
3. 검사 수행 및 검출 결과 확인

Test Environment
 - OS version
 - Kernel version

Founded bug:

**Comment by SomansaOpenSource** [comment]
done
